name: Pull from Apps Script and Auto-Commit

on:
  workflow_dispatch: {}   # 手動実行のみ

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install clasp
        run: npm i -g @google/clasp

      - name: Write ~/.clasprc.json from secret
        run: |
          mkdir -p ~/
          cat > ~/.clasprc.json << 'JSON'
          ${{ secrets.CLASPRC_JSON }}
          JSON

      - name: Write .clasp.json
        run: |
          cat > .clasp.json << JSON
          { "scriptId": "${{ secrets.SCRIPT_ID }}", "rootDir": "./" }
          JSON

      - name: Pull from GAS
        run: clasp pull

      - name: Auto commit if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: sync from GAS [skip deploy]"
          branch: main
          file_pattern: |
            *.gs
            *.js
            *.ts
            appsscript.json
